server:
  port: 8080

spring:
  application:
    name: hcbc

  datasource:
    url: jdbc:mysql://localhost:3306/hcbc_back_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root          # 네 MySQL 계정
    password: qaqawesd12@ # 네 MySQL 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379
      # password: 비번 쓰면 여기에

jwt:
  issuer: hcbc
  access-secret: hcbc-access-secret-key-2024-minimum-32-chars-required!
  refresh-secret: hcbc-refresh-secret-key-2024-minimum-32-chars-required!
  access-ttl: 1h      # 1시간
  refresh-ttl: 7d     # 7일
